"""rename address

Revision ID: 0e71e263415f
Revises: 200e7f3b710f
Create Date: 2023-12-06 12:23:42.893854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e71e263415f'
down_revision = '200e7f3b710f'
branch_labels = None
depends_on = None


# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('departments', sa.Column('location', sa.String(), nullable=False))
#     op.drop_column('departments', 'address')
#     # ### end Alembic commands ###


# def downgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('departments', sa.Column('address', sa.VARCHAR(), nullable=True))
#     op.drop_column('departments', 'location')
#     # ### end Alembic commands ###


# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('departments', schema=None) as batch_op:
#         batch_op.add_column(sa.Column('location', sa.String(), nullable=True))
#         batch_op.drop_column('address')

#     # ### end Alembic commands ###


# def downgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('departments', schema=None) as batch_op:
#         batch_op.add_column(sa.Column('address', sa.VARCHAR(), nullable=True))
#         batch_op.drop_column('location')

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###