"""rename department

Revision ID: 200e7f3b710f
Revises: 8ac62d41b027
Create Date: 2023-12-06 12:20:03.106005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '200e7f3b710f'
down_revision = '8ac62d41b027'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
